### ISSUE TITLE
Should we require the user to take the paper from the attic as well as the thread, before exiting? 

### ISSUE THREAD

**Issue by mccarrom** [ewk/adventure#50]
The paper has the list of things they need. If we don't want to require this, we can hide the list elsewhere throughout the house, or parts of the list elsewhere throughout the house, and that could be the clues in the shower, behind the wallpaper, and in the painting?

**Comment by BethMyre** [comment]
Maybe a prompt if they're missing the paper, like 'Before you leave, take a look around to see if there's anything else that could be useful.'
I think we should use the other clues to say where specific items are that might be hard to find.

**Comment by mccarrom** [comment]
prompt added in PR #86, does not prevent player from leaving
